name: Deploy Databricks Bundle

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Databricks CLI (v1)
        run: pip install --upgrade "databricks-cli>=0.205.0"

      - name: Validate Databricks bundle
        run: databricks bundle validate
        working-directory: dabproject1   # change if your folder name is different

      - name: Deploy Databricks bundle
        run: databricks bundle deploy
        working-directory: dabproject1

    env:
      DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}

